### ISSUE TITLE
Make editor toolbar take effect

### ISSUE THREAD

**Issue by linonetwo** [kookma/TW-Section#11]
Currently, there is no editor toolbar, and ctrl+2, ctrl+E, ctrl+U shortcut that work for editor toolbar is not taking effect too.

Do you think it is OK to add editor toolbar back, or use something like https://groups.google.com/g/tiddlywiki/c/1oFNPGtQj3c?pli=1 floating toolbar?

**Comment by kookma** [comment]
Editor toolbar and all keyboard shortcuts are supported!
Open https://kookma.github.io/TW-Section/
Goto Sidebar tab > More > Section editor
Select Main editor
Turn on Editor toolbar (or keep them off)

**Comment by linonetwo** [comment]
Thanks, then fishing and codemirror-enhanced will work with sections!
