### ISSUE TITLE
Compatibility issues with checklist plug in

### ISSUE THREAD

**Issue by arunnbabu81** [kookma/TW-Section#16]
I tried using section editor with checklist plug in. But the checklist doesn't work once i add the "se-type" field in that tiddler. 

"Ticked" todos get "unticked" automatically, if I close and re-open that tiddler or if I edit that tiddler. Sometimes it shows "Internal JavaScript Error " warning also. 

Also the sections and checklist items gets jumbled when the checklist is ticked if I don't add a line before the checklists.

Any idea what is causing this behaviour? I have attached a demo wiki

[Section and checklist.html.zip](https://github.com/kookma/TW-Section/files/7714026/Section.and.checklist.html.zip)

**Comment by kookma** [comment]
SE hides the text field of any tiddler and then parses the text field itself and splits it based on the headings!
It uses regsplit! but it does not change what you entered inside text field!
Checklist in other hand read text field and write to it, se it changes the text field! I am not familiar with JS, so I cannot find what is going behind!

I recommend to post the in checklist repo page! as SE works while checklist is installed!

By the way I will update SE to support the new cascade filter! please check also then!

**Comment by kookma** [comment]
Update:
I checked and see checklist and SE work with together as long as you do not use both in the same tiddler, so this is a good news!
