### ISSUE TITLE
Update plugin library

### ISSUE THREAD

**Issue by linonetwo** [kookma/TW-Section#19]
Hi Mohammad, seems you forget to update your plugin library, and I have been waiting for your update for a while...

![](https://user-images.githubusercontent.com/3746270/147584323-f3073745-2e8b-4ea2-8bc6-973eb2be008a.png)

**Comment by linonetwo** [comment]
Or maybe you can allow us config your plugin into our CPL, so it will auto update (in an hour) after you release it on the github.

You just need to release a JSON plugin (with fixed name so we can use that name to get it from the release), and I can do the rest for you.

Or you can try borrow the technique in our CPL to your plugin library, so yours can enjoy auto update too!

**Comment by kookma** [comment]
> Or maybe you can allow us config your plugin into our CPL

Sure, please feel free to include any of my plugins!
