### ISSUE TITLE
Use state tiddler

### ISSUE THREAD

**Issue by linonetwo** [kookma/TW-Section#20]
Hi, Is it possible use `$:/state/section-editor/xxx` instead of `$:/section-editor/state/xxx`?

So they won't be committed to the git...

![](https://user-images.githubusercontent.com/3746270/147586746-56da7fa3-dd60-4ebd-b2ed-5e30345d3f8b.png)

**Comment by linonetwo** [comment]
Or maybe they can be in a field of the tiddler? Not a separate tiddler.

**Comment by linonetwo** [comment]
Tiddlers starts with \`$:/\` won't show up in the disk when using nodejs wiki, and won't cause data leak if we use fileSystemPath to put the tiddler in a different folder.

Currently, the state tiddler of SE will go into different folder than the original tiddler, because it have different tags than the original tiddler, so won't be recognized by fileSystemPath to automatically move it.

**Comment by linonetwo** [comment]
![截屏2022-01-19 上午10 53 58](https://user-images.githubusercontent.com/3746270/150055108-4001d89b-5df7-46e1-b682-0dc1350ec4b0.png)

Is this what you are concerning?

But I think in sections, editing is small enough, so loosing them is acceptable, and this is very rare.

Even we want to keep the edit state tiddler, maybe view state tiddler can still be in $:/state

**Comment by kookma** [comment]
> Tiddlers starts with `$:/` won't show up in the disk when using nodejs wiki, and won't cause data leak if we use fileSystemPath to put the tiddler in a different folder.

I agree! just let me do a cross check!
