### ISSUE TITLE
Should be filterpattern

### ISSUE THREAD

**Issue by linonetwo** [kookma/TW-Section#29]
[https://github.com/kookma/TW-Section/blob/c44fb1c497381019bd576f82f6cd93098b749a8b/source/section/viewtemplates/sections.tid#L13](https://github.com/kookma/TW-Section/blob/c44fb1c497381019bd576f82f6cd93098b749a8b/source/section/viewtemplates/sections.tid#L13)

You typo filterpatern , lol

**Comment by linonetwo** [comment]
I'm searching in your code to learn how to change view template body when adding field `se-type`

Because I want to change to WYSIWYG editor after adding field `wysiwyg`

**Comment by kookma** [comment]
@linonetwo 
Have you got how the viewTemplate changes? It uses cascades!

**Comment by kookma** [comment]
> You typo filterpatern , lol

Thank you, I correct it! Will see it in next update!
