### ISSUE TITLE
Conflict with tiddlywiki/freelinks plugins

### ISSUE THREAD

**Issue by byzheng** [kookma/TW-Section#31]
System information: Latest TW section after tiddlywki 5.2.2 with node.js 2.0.16 under windows 10

Step to reproduce this bug.

* Enable "tiddlywiki/freelinks" in the file `tiddlywiki.info`.
* Edit the `non-first` section/subsection in a tiddler (the first section is working).
* Type any character in the editor. 
* The edit area will loss focus and cannot type any new characters.

**Comment by kookma** [comment]
I do not use Freelink plugin. I will give a try! Stay tunned

**Comment by DigitalSorcerer4225** [comment]
This happens to me too. Are there any updates to this issue?

**Comment by kookma** [comment]
I am not sure if this issue is because of TW-Section. So would you please raise this issue in talk.tiddlywiki.org forum and see what developers say!

**Comment by kookma** [comment]
Has the issue resolved? I recommend post on Talk.

**Comment by byzheng** [comment]
Thanks for reminders. I don't use freelinks and section editor now.
