### ISSUE TITLE
Edit Toolbar Configuration button is ignored. 

### ISSUE THREAD

**Issue by Marxsal** [kookma/TW-Section#32]
The Edit Toolbar shows up whether or not you toggle the "Turn on editor toolbar" button.
Also, when using simple text area, you have no toolbar (maybe it's always been like that?).

**Comment by kookma** [comment]
Thank you Mark. I will investigate.

> The Edit Toolbar shows up whether or not you toggle the "Turn on editor toolbar" button.
Thank you I will investigate and back to you.

> Also, when using simple text area, you have no toolbar (maybe it's always been like that?).
Yes, the simple editor has no toolbar! It is a simple text area!

**Comment by kookma** [comment]
issue fixed in TW-Section 1.1.1
