### ISSUE TITLE
Demo is one version ahead of github code ?

### ISSUE THREAD

**Issue by Marxsal** [kookma/TW-Section#36]
It appears that the github code is at version 1.1.1, but the Demo is at 1.1.2. And there appears to be a slight bug in the presentation of previews in 1.1.1.  The demo version appears to be condensed (uglified?), so it's not easy to work with.

Would it be possible to update the code base to 1.1.2 ?

Thank you!

**Comment by kookma** [comment]
Sure, I have noticed lately that the Uglify makes some compressed macros and tiddler do not work correctly! I used uglified version for demo and drag and drop install with "small is better" in mind!

I will update to the latest version this weekend!

**Comment by kookma** [comment]
The release is not compressed and updated to TW 5.3.3
