### ISSUE TITLE
[1.2.0] Editor preview appears below instead of beside the editor text

### ISSUE THREAD

**Issue by Vingolf** [kookma/TW-Section#39]
At first, I like the section editor and it is a very useful tool 👍

After upgrading from 1.1.2 to 1.2.0 I discovered that the preview pane appears below the editor:

**Section Editor 1.1.2**
![Section-Editor-1 1 2a](https://github.com/kookma/TW-Section/assets/56415645/a070209c-31ef-4a1e-b032-ef0ec6e84e4c)

**Section Editor 1.2.0**
![Section-Editor-1 2 0](https://github.com/kookma/TW-Section/assets/56415645/6ca3c0d6-8795-42fc-8054-b02c0e3afd04)

TW v.5.3.x on Windows 10

**Comment by kookma** [comment]
This is a bug with TW 5.3.3.
I will investigate!

**Comment by kookma** [comment]
Update 1.2.1 fixed the issue!

**Comment by Vingolf** [comment]
> Update 1.2.1 fixed the issue!

Thank you for your quick response 😃

Section  Editor 1.2.1
![Section-Editor-1 2 1](https://github.com/kookma/TW-Section/assets/56415645/8537b13e-92d6-4e9a-92b1-598f4a5d3c91)

It is working now as expected 🥳️
