### ISSUE TITLE
Plugin Status: required tiddlywiki version differs

### ISSUE THREAD

**Issue by Vingolf** [kookma/TW-Section#40]
According to the [Plugin Status](https://kookma.github.io/TW-Section/#Plugin%20Status) of the Section Editor Plugin v1.2.0 the Tiddlywiki version **5.2.0+** is required.

I have noticed a difference to the required tiddlywiki version of the Section Editor itself:

{{$:/plugins/kookma/utility!!core-version}} is **>=5.2.5**

So I am not sure, which version of Section Editor can be used with Tiddlywiki v.5.2.1 🤔

Edit: 
A similar issue applies to the [Utility Plugin](https://kookma.github.io/TW-Utility/#Plugin%20Status)

**Comment by kookma** [comment]
I will correct this, both should be the same. You can go to https://github.com/kookma/TW-Section/releases and select the right release. By the way the Plugin Status is old and shall be updated the core version is more precise.
