### ISSUE TITLE
Add list-after field to $:/plugins/kookma/section/viewtemplates/sections

### ISSUE THREAD

**Issue by Gk0Wk** [kookma/TW-Section#8]
The list widget uses the `list-after` field to control the order of tiddlers in `<$list>`. I suggest that `$:/plugins/kookma/section/viewtemplates/sections` should add this field so that `list-after` has the value `$:/core/ui/ViewTemplate/body` to indicate the Section's ViewTemplate immediately after the tiddler's body.

Without adding this field, Sections are sometimes listed after other custom ViewTemplates, such as [CrossLinks](https://github.com/akhater/TWCrossLinks):

![image](https://user-images.githubusercontent.com/16955102/138058731-83ef23ff-e7e6-4775-ad75-50aa9710dc7c.png)

After adding `list-after` field:

![image](https://user-images.githubusercontent.com/16955102/138058872-74e5fd00-c8dd-4d93-a7fa-f1d20cb18dd0.png)

**Comment by kookma** [comment]
Ah goof catch! 
Sure I  fix it!
